import "./globals.css";
import LayoutWrapper from "./common/layoutwrapper";
import { WalletProvider } from "./context/walletcontext";
import Script from "next/script";

export const metadata = {
  title: "Dhanbady",
  description: "Generated by bharatgrow",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://accounts.google.com/gsi/client"
          strategy="beforeInteractive"
        />
      </head>
      <body>
        <WalletProvider>
          <LayoutWrapper>
            {children}
          </LayoutWrapper>
        </WalletProvider>
      </body>
    </html>
  );
}